language: php

php:
  - '7.2'
  - hhvm
  - nightly

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-7.1.3.phar
  - composer install

script: phpunit --testdox tests